export {default as NavBar} from './NavBar'
export {default as Carrousel} from './Carrousel'
export {default as Cursos} from './Cursos'
export {default as Medicina} from './Medicina'
export {default as Taichi} from './Taichi'
export {default as Contacto} from './Contacto'